version: "3"

services:
  app:
      build:
        context: .
      ports:
        - "8001:8001"
      volumes:
        - ./app:/app
      command: >
        sh -c " python manage.py runserver 127.0.0.1:8001"
